# Generated by Django 5.1.4 on 2024-12-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_anime_anime_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime_item',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='anime_item',
            name='reyting',
        ),
        migrations.RemoveField(
            model_name='serial_item',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='serial_item',
            name='reyting',
        ),
        migrations.AlterField(
            model_name='kinolar',
            name='video_fayl',
            field=models.FileField(max_length=600, upload_to='kino/'),
        ),
    ]
